theme: jekyll-theme-minimal
title: [Autocomplete Rescue for Xcode]
description: [Restore Xcode autocomplete with this menubar extension]
logo: [autocomplete-rescue-web-logo.png]
show_downloads: [true]
